name: run main.py

on: 
  workflow_dispatch:
  schedule:
    - cron: '58 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        run: python main.py >> log_file.log
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update data
